language: objective-c
install:
    - gem install cocoapods --pre
before_script:
    - rm -rf ~/Library/Developer/Xcode/DerivedData
script:
    - cordova create app
    - cd app
    - cordova platform add android
    - cordova platform add ios
    - cordova plugin add https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core.git#development
    - cordova build 