language: objective-c
matrix: 
    include:
        - osx_image: xcode7.3
        - osx_image: xcode8
install:
    - gem install cocoapods --pre
before_script:
    - rm -rf ~/Library/Developer/Xcode/DerivedData
    - npm install -g cordova
script:
    - cordova create app
    - cd app
    - cordova platform add android
    - cordova platform add ios
    - cordova plugin add https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core.git#development
    - cordova build 