language: objective-c
install:
    - gem install cocapods --pre
before_script:
    - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
script:
    - cordova create app
    - cd app
    - cordova platform add android
    - cordova platform add ios
    - cordova plugin add https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core.git#development
    - cordova build 