language: objective-c
matrix:
    include:
        - osx_image: xcode7.3
        - osx_image: xcode8
install:
    - gem install cocoapods --pre
before_script:
    - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
    - tar xzf android-sdk_r24.4.1-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - echo "yes" | android update sdk --filter platform-tools,extra-google-m2repository,extra-android-m2repository,build-tools-24.0.3,android-23,extra-android-support --no-ui --all --force
    - rm -rf ~/Library/Developer/Xcode/DerivedData
    - npm install -g cordova
script:
    - cordova create app
    - cd app
    - cordova platform add android
    - cordova platform add ios
    - cordova plugin add https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core.git#development
    - cordova build android
    - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
       cd ~/Documents;
       git clone https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core.git;
       cd bms-clientsdk-cordova-plugin-core;
       echo $token >> $HOME/.npmrc;
       npm publish;
      fi
after_script:
    - if [ -f $HOME/.npmrc ] && [ ! -z "$(tail -n 1 $HOME/.npmrc | grep _authToken)" ]; then
       echo "Found token in .npmrc";
       sed -i '$d' $HOME/.npmrc > $HOME/.npmrc.bk;
       cp $HOME/.npmrc.bk $HOME/.npmrc;
       rm $HOME/.npmrc.bk;
      fi