language: objective-c
install:
    - gem install cocapods --pre
    - brew update
    - brew install wget
    - brew install npm
    - npm install -g cordova
before_script:
    - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
    - tar xzf android-sdk_r24.4.1-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - android list sdk
    - android update sdk --filter platform-tools,android-15,android-21,android-23,extra-android-support --no-ui --force
    - rm -rf ~/Library/Developer/Xcode/DerviedData
    - pod setup

script:
    - cordova create app
    - cd app
    - cordova platform add android
    - cordova platform add ios
    - cordova plugin add https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core.git#development
    - cordova build 